"""Simple entry

Revision ID: 6ffbe54fd602
Revises: 
Create Date: 2021-10-05 04:32:27.277282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ffbe54fd602'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('reading_el', sa.String(), nullable=True),
    sa.Column('kanji_el', sa.String(), nullable=True),
    sa.Column('sense', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    # ### end Alembic commands ###
